ChartValues:
  replicaCount:
    Ref: ReplicaCount
  service:
    port: 8080
    type: LoadBalancer
HelmChartPath: Chart
RuntimeType: Kubernetes
ServiceType: private
OutputCmd: |-
  export SERVICE_IP=$(kubectl get svc --namespace ${Namespace} spring-boot-chart -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo "Visit URL: http://$SERVICE_IP:8080/"
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: yehanyh/spring-boot-chart
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: Number
  AllowedPattern: ''
  Label: Pod数
  ConstraintDescription: ''
  Default: '1'
  Name: ReplicaCount
OutputType: OutputCommand
Owner: yehanyh
Branch: main
Platform: github
